const USER_TYPES = {
    USER: 1,
    ADMIN: 2
};

const ROLES = {
    ADMIN: 1,
    SUBADMIN: 2,
    USER: 3,
    BUSINESS: 4
}

 const JWT = {
    USER_SECRET: "USER_SECRET",
    ADMIN_SECRET: "ADMIN_SECRET",
    EXPIRES_IN: 10000,
}

const GENDER = {
    MALE: 1,
    FEMALE: 2,
    OTHER: 3,
}

const OTP_FOR = {
    REGISTER: 1,
    LOGIN: 2,
    FORGOT_PASSWORD: 3,
    VERIFICATION: 4,
}

const RESPONSE_STATUS = {
    SUCCESS: 1,
    FAILURE: 2,
    INTERNAL_SERVER_ERROR: 3,
    BAD_REQUEST: 3,
    RECORD_NOT_FOUND: 4,
    VALIDATION_ERROR: 5,
    UNAUTHORIZED: 6,
    ALREADY_EXISTS: 7
}

const RESPONSE_STATUS_CODE = {
    SUCCESS: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    ALREADY_EXISTS: 409,
    VALIDATION_ERROR: 422,
    INTERNAL_SERVER_ERROR: 500
}

module.exports = { USER_TYPES,ROLES, GENDER,OTP_FOR, JWT,RESPONSE_STATUS, RESPONSE_STATUS_CODE };
